inherit_from: https://gitlab.com/ekylibre/tools/rubocop/-/raw/0.2.0/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'

Naming/FileName:
  Exclude:
    - 'lib/lexicon-common.rb'
